- internal/scylla/client.go
If not closed it affects http connection reuse.
> internal: close response body after reading it

- internal/provider/provider.go
- internal/scylla/client.go
As configure function is being called more than once on the same client it was adding duplicated headers. This in turn was making some request receive 400 response code from api endpoint.
Fixes https://github.com/scylladb/terraform-provider-scylladbcloud/issues/29
> internal: don't duplicate http headers

- .gitignore
- internal/provider/cluster.go
- internal/scylla/model/model.go
Without this there is no easy way to connect to the cluster. I didn't add public IPs as this is not encouraged config. Theoretically private IPs could also be skipped but my yscb setup doesn't want to work with DNS out of the box.
> provider: add computed values for cluster private IPs and DNS

- internal/scylla/client.go
- internal/scylla/cloudmeta.go
- internal/scylla/codes.txt
- internal/scylla/errcode.go
- internal/scylla/errcode_test.go
Fixes #50
The codes.txt is created by copying the text content of the following element:
//*[@id="swagger-ui"]/section/div[2]/div[2]/div[1]/section/div/div/div/div/pre/code/text()
From the following document:
https://api.cloud.scylladb.com/docs/swagger.json
> internal/scylla: add err codes mapping to metadata

- internal/provider/allowlist_rule.go
- internal/provider/cluster.go
- internal/provider/cql_auth_data_source.go
- internal/provider/vpc_peering.go
- internal/scylla/client.go
- internal/scylla/cloudmeta.go
- internal/scylla/endpoints.go
fixes #44 
Also addresses `Cloudmeta` nilness check which in my case was needed before calling `findAndSaveAccountID` in order to fix panic cased by nil `c.Meta.ErrCodes`
```go
if c.Meta == nil {
var err error
if c.Meta, err = BuildCloudmeta(ctx, c); err != nil {
return fmt.Errorf("error building metadata: %w", err)
}
}
```
and 
```go
if data.Error != "" {
return makeError(data.Error, c.Meta.ErrCodes, resp)
}
```
> feat: add support for context.Context to scylla provider and http client

- .golangci.yml
- internal/provider/allowlist_rule.go
- internal/provider/cluster.go
- internal/provider/cql_auth_data_source.go
- internal/provider/serverless_bundle_data_source.go
- internal/provider/serverless_cluster.go
- internal/provider/vpc_peering.go
closes #https://github.com/scylladb/terraform-provider-scylladbcloud/issues/71 
closes #https://github.com/scylladb/terraform-provider-scylladbcloud/issues/65
This PR enables `errcheck` linter back and handles/discards error coming from `ResourceData.Set` and deletes `.golangci.yml` since currently there's no need to configure `golangci-lint` at all, alternatively we could handle the errors with go 1.20 `errors.Join` like so since it only slightly reduces readability
```go
err := errors.Join(
d.Set("cluster_id", cluster.ID),
d.Set("name", cluster.ClusterName),
d.Set("cloud", p.CloudProvider.Name),
d.Set("region", cluster.Region.ExternalID),
)
if err != nil {
return err
}
```
> chore(lint): enable errcheck and discard errors for ResourceData.Set

- docs/index.md
This commit updates the landing page of the provider documentation with the basic information.
In addition, I've added a new section with the links that may be useful to the provider users.
> doc: update the provider documentation index page

- docs/resources/vpc_peering.md
- internal/provider/vpc_peering.go
- internal/provider/vpc_peering_test.go
This PR adds new attribute to VPC peering called `peer_cidr_blocks` that allows users to specify multiple CIDR blocks using much nicer list syntax instead of comma separated strings and `peer_cidr_block`
Manifest
```tf
resource "scylladbcloud_cluster" "cluster" { ... }
resource "scylladbcloud_vpc_peering" "multi-block-peering" {
...
peer_cidr_blocks = ["10.90.5.0/25", "10.76.8.0/25"]
...
}
```
---
`tf apply`
```
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
Outputs:
scylladbcloud_cluster_id = "243"
scylladbcloud_vpc_peering_connection_id = "pcx-052110a57ab55aa72"
```
---
`tf destroy`
```
Destroy complete! Resources: 2 destroyed.
```
And internally it creates peering with this list `["10.90.5.0/25","10.76.8.0/25"]`
Still I'm wondering if we need to take any additional …
> feat(peering): add peer_cidr_blocks attribute for VPC peering

- internal/provider/cluster.go
- internal/provider/serverless_cluster.go
Fixes https://github.com/scylladb/terraform-provider-scylladbcloud/issues/85
> fix(serverless): catch 400001 error when cluster is gone

- internal/scylla/client.go
There are two problems with what it does on `http.StatusTooManyRequests`:
1. It does not retry
2. It does not wait
I have also found that if request is failed, then it is retrying without waiting, which is also a problem.
> fix(api-client): handle `http.StatusTooManyRequests`

- docs/resources/serverless_cluster.md
- internal/provider/cluster.go
- internal/provider/serverless_cluster.go
- internal/scylla/client.go
- internal/scylla/errors.go
- internal/scylla/model/model.go
There is plan to use terraform script to test serverless bootstraping.
In order to have it we need pu and expiration time exposed
> fix(serverless): add processing units and expiration time for serverless

- internal/provider/cluster.go
- internal/provider/serverless_cluster.go
Fixes #101 
tf plugin fails on internal validation:
```
resource scylladbcloud_cluster: All fields are ForceNew or Computed w/out Optional, Update is superfluous
```
Reason for it is that there are no fields that could be updated not triggering renew, which is correct, since `siren` have no api to `update` cluster.
But #88 left `update`-related fields in the cluster resource, which triggers tf validator to fail
> fix(cluster): fix internal validation failure

- internal/provider/cluster.go
- internal/provider/vpc_peering.go
- internal/scylla/model/model.go
close https://github.com/scylladb/terraform-provider-scylladbcloud/issues/107
This PR adds support/fixes for:
- `AllowCQL` property for VPC Peering resource
- `AlternatorWriteIsolation` property for cluster resource
These properties were never assigned properly when fetching a resource from Scylla Cloud APIs
context: https://github.com/scylladb/siren-frontend/pull/4102
> fix: handle AllowCQL and AlternatorWriteIsolation on resource read

- .github/workflows/go.yml
- go.mod
- go.sum
- internal/scylla/client.go
- internal/scylla/retry.go
Supersedes #100.
This PR introduces configurable retry mechanism, which can be used to implement more complex retry logic.
Currently the retry policy is as follows:
- we are going to retry on temporary network errors (dial error, broken tcp etc.)
- we are going to retry on known http statuses (which have limited effect now)
- we are going to retry on known ScyllaDB Cloud API error codes
> internal/scylla: introduce proper retry mechanism

- .github/workflows/go.yml
- docs/resources/cluster.md
- internal/provider/cluster/cluster.go
- internal/provider/cluster/cluster_v0.go
- internal/scylla/cloudmeta.go
Scylla Cloud has multiple storage size options available for the same `node_type` attributes that currently cannot be selected in the case of the `GCP` provider. For example, `n2-highmem-8` has five distinct storage size options: 375, 750, 1500, 3000, and 6000.
This pull request adds an optional `node_disk_size` attribute that gives the ability to select other storage options.
> [!IMPORTANT]  
> `node_disk_size` must match exactly. If there's no instance with a particular, storage size option, the operation will fail.
Discussion and decisions leading to this implementation can be found in the internal issue with reference number 10003.
As GCP has multiple storage options for the same instance name, I've fetched the list of instances for `us-west-1` region and decided to pick one with 2+ …
> feat: add the optional node_disk_size attribute

- docs/data-sources/cql_auth.md
- internal/provider/cluster/cluster.go
- internal/provider/cqlauth/cql_auth_data_source.go
- internal/provider/cqlauth/cql_auth_data_v0.go
Fixes:
https://github.com/scylladb/terraform-provider-scylladbcloud/issues/116
https://github.com/scylladb/terraform-provider-scylladbcloud/issues/130
Tested:
main.tf:
```
resource "random_string" "postfix" {
length           = 8
special          = false
}
resource "scylladbcloud_cluster" "aws" {
name       = "AWS-statuspage-test2-${random_string.postfix.result}"
cloud      = "AWS"
region     = "us-east-1"
node_count = 3
node_type  = "t3.micro"
cidr_block = "172.31.0.0/24"
enable_dns = true
}
data "scylladbcloud_cql_auth" "example" {
cluster_id = scylladbcloud_cluster.aws.id
}
```
Steps for `upgrade scenario`:
1. Run `tf init; tf apply`, on current version (`1.5.0`) of terraform provider
2. Upgrade tf provider and run `tf apply`
Steps for `create scenario`:
1. Upgrade tf provider and run …
> internalprovider: fix inconsistent datacenter references

- internal/provider/cluster/cluster.go
- internal/scylla/errors.go
Closes #134 
main.tf:
```
resource "scylladbcloud_cluster" "aws" {
name       = "test-cluster"
cloud      = "AWS"
region     = "us-east-1"
node_count = 3
node_type  = "t3.micro"
cidr_block = "172.31.0.0/24"
enable_dns = true
}
```
Steps to reproduce:
1. `terraform apply`
2. Delete cluster on UI
3. `terraform destroy`
Currently endup in error:
```
│ Error: error reading cluster: Error "": CLUSTER_DELETED (http status 200, method GET url "https://app-api-dkropachev.ext.lab.scylla.cloud/account/100165/cluster/292?enriched=true")
│ 
│   with scylladbcloud_cluster.aws,
│   on main.tf line 6, in resource "scylladbcloud_cluster" "aws":
│    6: resource "scylladbcloud_cluster" "aws" {
│ 
╵
```
> fix(cluster): make it treat deleted cluster properly

- internal/provider/vpcpeering/vpc_peering.go
Closes #137
Covers two scenarios:
First scenario
1. Cluster and VPC Peering is created by terraform
2. VPC Peering is deleted, on the scylla cloud via something else but terraform.
3. `terraform apply`, that should recreate it
Second scenario
1. Cluster and VPC Peering is created by terraform
2. Cluster is deleted, on the scylla cloud via something else but terraform.
3. `terraform apply`, that should recreate it
> fix(vpc-peering): delete state when object is deleted from the scylla cloud

- CODEOWNERS
- internal/provider/provider.go
- internal/provider/stack/stack.go
- internal/scylla/client.go
- internal/scylla/model/model.go
- internal/scylla/v2/options.go
- internal/scylla/v2/scylla.go
This PR adds a "scylladbcloud_stack" resource which is used for accounting managed resources with the Stacks API.
It uses new client, as the payloads for Stacks API are HMAC signed.
> provider/stack: add new stack resource for Stacks API integration

- .github/workflows/release.yml
Fixes the following release error:
⨯ command failed  error=unknown flag: --rm-dist
github.com/scylladb/terraform-provider-scylladbcloud/actions/runs/9906794216/job/27369116319
> github/workflows: update release action

- .goreleaser.yml
Fixes the following error:
release failed after 0s  error=only configurations files on version: 2 are supported, yours is version: 0, please update your configuration
github.com/scylladb/terraform-provider-scylladbcloud/actions/runs/9906916864/job/27369488526
> github: update goreleaser config

- .github/workflows/go.yml
- internal/provider/connection/connection.go
Fixes https://github.com/scylladb/terraform-provider-scylladbcloud/issues/179.
> internal/provider/connection: fix lint warnings

- internal/provider/cluster/cluster.go
- internal/provider/serverless/serverless_cluster.go
- internal/scylla/model/model.go
[#12512](https://github.com/scylladb/siren/issues/12512)
userFriendlyError was not used for 2 years, 
and if the terraform action failed, there would be an empty error
I propose to add ClusterRequest.ID so the user will have something to hang on to
> remove userFriendlyError, filed was empty and is deprecated

- README.md
The old link is broken; let's have the correct one.
> docs(readme): Update Scylla Cloud API Token link
